### ISSUE TITLE
The getter 'iterator' was called on null.

### ISSUE THREAD

**Issue by m7md10** [ahmedgulabkhan/TouristAssist#2]
hello ! I'm getting this error after signing up (in ) as a Tourist 

`> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building TouristHomePage(dirty, dependencies:
[_InheritedTheme, _LocalizationsScope-[GlobalKey#9c877]], state: _TouristHomePageState#33923):
The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
The relevant error-causing widget was:
  TouristHomePage`
 

Also there is an error when loading the app for first run , 
`Failed Assertion: Boolean expression must not be null'
it seems that result in _getIsLoggedIn() is returning null , so I did the following to fix that error , I'm still learning and I don't really know if this is a good approach ;)

`
  _getIsLoggedIn() async {
    await HelperFunctions.getUserLoggedInSharedPreference().then((result) {
      if (result != null) {
        setState(() {
          _isLoggedIn = result;
        });
      }
    });
`

thank you for sharing this project !

UPDATE :

Eror fixed by editing 

> if(_guides != []) 
line 73
to

>  if(_guides != null)

**Comment by ahmedgulabkhan** [comment]
Thanks a lot @m7md10 for raising the issue and fixing it, I will now change that part of the code :)
